### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by sebastianst** [perun-network/erdstall#45]
Taking some standard CI config from some of our public Go projects, including
* tests
* vetting

**Comment by ggwpez** [comment]
We do need a `ganache-cli` for the tests, right? @sebastianst

**Comment by sebastianst** [comment]
I think the operator tests currently do need it, yeah...

**Comment by ggwpez** [comment]
We discussed to use github since the Travis jobs were in the pipeline for hours. I changed the title of the issue.
